name: Test FastAPI NVG Endpoint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-nvg-api:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install test tools
      run: pip install requests pytest numpy

    - name: Build Docker image
      run: docker build -t sl-nvg ./nvg-endpoint

    - name: Run container
      run: docker run -d -p 8000:8000 --name sl-nvg sl-nvg

    - name: Wait for API to be Ready
      run: |
        for i in {1..10}; do
          if curl -s http://localhost:8000/docs; then
            echo "API is up!"
            break
          fi
          echo "Waiting for API..."
          sleep 3
        done

    - name: Run API test
      run: pytest tests/

    - name: Cleanup
      run: |
        docker stop sl-nvg
        docker rm sl-nvg